/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TodoApp2;

import java.sql.Connection;
import util.ConnectionFactory;



public class App {
  
    public static void main(String[] args) {
        
        Connection connection = ConnectionFactory.getConnection();
        
            ConnectionFactory.closeConnection(connection);
        
        
        
        
    }
}
